name: amazon_s3
version: 0.1.7
author: Clean Team <clean@vacuumlabs.com>
description: Amazon S3 API
homepage: http://vacuumlabs.com/
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  clean_router: ">=0.3.6 <0.4.0"
  crypto: '>=0.9.0 <0.10.0'
  logging: ">=0.9.2 <0.10.0"
  quiver: ">=0.18.2 <0.19.0"
  xml: ">=2.0.0 <3.0.0"
