name: amazon_s3
version: 0.0.1
author: Clean Team <clean@vacuumlabs.com>
homepage: http://vacuumlabs.com/
description: Amazon S3 API
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  crypto: '>=0.9.0 <0.10.0'
  intl: any
